language: python
python:
    - "3.4"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
    - "pip install --upgrade pip"
install:
    - "pip install -r requirements.txt"
script:
    - "make test"
