# Intended to install tarsnap on the remote machine, can be removed once we rewrite
# bin/bootstrap to use ansible.
# In the meantime if you need bootstrap in your local enviorment please
# run: ansible-playbook install_tarsnap.yml -i localhost, -e "ansible_port=2222" --ssh-common-args "-o UserKnownHostsFile=no -o StrictHostKeyChecking=no" -vvvv -u vagrant

- name: Install Python 2 on target machine
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - raw: sudo apt-get update -qq && sudo apt-get install -qq python

- name: Deploy the OpenCraft Instance Manager
  hosts: all
  become: true
  roles:
    - pmbauer.tarsnap
