- name: Deploy the OpenCraft Instance Manager
  hosts: all
  become: true
  roles:
    - name: common-server
      COMMON_SERVER_NO_BACKUPS: true    # The instance manager VM is stateless
      FORWARD_MAIL_MYDOMAIN: "{{ inventory_hostname }}"
      UNATTENED_UPGRADES_ERRORS_RELAY_TO: "{{ inventory_hostname }}"
    - name: geerlingguy.nginx
      nginx_remove_default_vhost: true
    - opencraft
