# Note: due to security concerns we prefer using git hashes than ansible versions for
# roles not managed by OpenCraft.

- name: geerlingguy.security
  src: https://github.com/geerlingguy/ansible-role-security
  version: af8b13833290ccae2ce1d2c9cce78862ddd3666c

- name: kamaln7.swapfile
  src: https://github.com/kamaln7/ansible-swapfile
  version: 8eb0e18d90a7f25b6658fbf56bcba01b84a664fc

- name: pmbauer.tarsnap
  src: https://github.com/pmbauer/ansible-tarsnap
  version: 7a625912409a0be2a3bf48967c60c5328ae2f3b2

- name: backup-to-tarsnap
  src: https://github.com/open-craft/ansible-backup-to-tarsnap
  version: origin/master

- name: common-server
  src: https://github.com/open-craft/ansible-common-server
  version: origin/master

- name: configure-apt
  src: https://github.com/open-craft/ansible-configure-apt
  version: origin/master

- name: sanity-checker
  src: https://github.com/open-craft/ansible-sanity-checker/
  version: origin/master

- name: forward-server-mail
  src: https://github.com/open-craft/ansible-forward-server-mail
  version: origin/master

- name: consul
  src: https://github.com/open-craft/ansible-role-consul
  version: origin/master

- name: opencraft
  src: https://github.com/open-craft/ansible-opencraft
  version: origin/master
