---
# Playbook to add/remove a vhost and a set of associated users from a RabbitMQ instance.

- hosts: all
  become: True
  vars:
    STATE: present
    RABBITMQ_VHOST: /test
    RABBITMQ_USERS: []
  tasks:
    - name: add/remove vhost
      rabbitmq_vhost:
        name: "{{ RABBITMQ_VHOST }}"
        state: "{{ STATE }}"

    - name: add/remove users
      rabbitmq_user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        tags: "administrator,{{ item.username }}"
        vhost: "{{ RABBITMQ_VHOST }}"
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: "{{ STATE }}"
      with_items: "{{ RABBITMQ_USERS }}"
