AWS_ACCESS_KEY_ID: '{{ instance.s3_access_key }}'
AWS_SECRET_ACCESS_KEY: '{{ instance.s3_secret_access_key }}'

EDXAPP_AWS_ACCESS_KEY_ID: '{{ instance.s3_access_key }}'
EDXAPP_AWS_SECRET_ACCESS_KEY: '{{ instance.s3_secret_access_key }}'
EDXAPP_AUTH_EXTRA:
  AWS_STORAGE_BUCKET_NAME: '{{ instance.s3_bucket_name }}'

XQUEUE_AWS_ACCESS_KEY_ID: '{{ instance.s3_access_key }}'
XQUEUE_AWS_SECRET_ACCESS_KEY: '{{ instance.s3_secret_access_key }}'
XQUEUE_S3_BUCKET: '{{ instance.s3_bucket_name }}'
XQUEUE_S3_PATH_PREFIX: 'xqueue'

EDXAPP_GRADE_STORAGE_TYPE: 's3'
EDXAPP_GRADE_BUCKET: '{{ instance.s3_bucket_name }}'
EDXAPP_GRADE_ROOT_PATH: 'grades-download'

# Tracking logs
COMMON_OBJECT_STORE_LOG_SYNC: true
COMMON_OBJECT_STORE_LOG_SYNC_BUCKET: '{{ instance.s3_bucket_name }}'
COMMON_OBJECT_STORE_LOG_SYNC_PREFIX: 'logs/tracking/'
AWS_S3_LOGS_ACCESS_KEY_ID: '{{ instance.s3_access_key }}'
AWS_S3_LOGS_SECRET_KEY: '{{ instance.s3_secret_access_key }}'
