# Simple-theme (created from SASS variables at deploy time)

{% if application %}
# These settings come from the instance registration form
SIMPLETHEME_SASS_OVERRIDES:
  - variable: link-color
    value: '{{ application.link_color }}'
  - variable: header-bg
    value: '{{ application.header_bg_color }}'
  - variable: footer-bg
    value: '{{ application.footer_bg_color }}'
  - variable: button-color
    value: '{{ application.main_color }}'
  - variable: action-primary-bg
    value: '{{ application.main_color }}'
  - variable: action-secondary-bg
    value: '{{ application.main_color }}'

SIMPLETHEME_STATIC_FILES_URLS:
  - url: '{{ application.logo.url }}'
    dest: lms/static/images/logo.png
  - url: '{{ application.favicon.url }}'
    dest: lms/static/images/favicon.ico

SIMPLETHEME_ENABLE_DEPLOY: True

{% else %}

# Instance wasn't created from application form, so no colors will be set or changed
# and simple_theme won't be used (unless manually requested through other settings).

{% endif %}
