# System
COMMON_HOSTNAME: '{{ instance.domain }}'

# edxapp
EDXAPP_PLATFORM_NAME: "{{ instance.name }}"
EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_PREVIEW_NGINX_PORT: 80
EDXAPP_CMS_NGINX_PORT: 80
EDXAPP_SITE_NAME: '{{ instance.domain }}'
EDXAPP_LMS_SITE_NAME: '{{ instance.domain }}'
EDXAPP_LMS_BASE: '{{ instance.domain }}'
EDXAPP_PREVIEW_LMS_BASE: '{{ instance.lms_preview_domain }}'

EDXAPP_CMS_SITE_NAME: '{{ instance.studio_domain }}'
EDXAPP_CMS_BASE: '{{ instance.studio_domain }}'

# Enable OpenStack settings to be able to use Swift.  These three variables are ignored in versions
# of the configuration repo that don't have the openstack role yet, so it's safe to include them.
EDXAPP_SETTINGS: 'openstack'
XQUEUE_SETTINGS: 'openstack_settings'
COMMON_VHOST_ROLE_NAME: 'openstack'

# Forum environment settings
FORUM_RACK_ENV: 'production'
FORUM_SINATRA_ENV: 'production'

# Emails
EDXAPP_CONTACT_EMAIL: '{{ appserver.email }}'
EDXAPP_TECH_SUPPORT_EMAIL: '{{ appserver.email }}'
EDXAPP_BUGS_EMAIL: '{{ appserver.email }}'
EDXAPP_FEEDBACK_SUBMISSION_EMAIL: '{{ appserver.email }}'
EDXAPP_DEFAULT_FROM_EMAIL: '{{ appserver.email }}'
EDXAPP_DEFAULT_FEEDBACK_EMAIL: '{{ appserver.email }}'
EDXAPP_SERVER_EMAIL: '{{ appserver.email }}'
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: '{{ appserver.email }}'

# Misc
EDXAPP_TIME_ZONE: 'UTC'

# Security updates
COMMON_SECURITY_UPDATES: true
SECURITY_UNATTENDED_UPGRADES: true
SECURITY_UPDATE_ALL_PACKAGES: false
SECURITY_UPGRADE_ON_ANSIBLE: true

# Repositories URLs
edx_ansible_source_repo: '{{ appserver.configuration_source_repo_url }}'
edx_platform_repo: '{{ appserver.edx_platform_repository_url }}'

# Pin down dependencies to specific (known to be compatible) commits.
edx_platform_version: '{{ appserver.edx_platform_commit }}'
configuration_version: '{{ appserver.configuration_version }}'
forum_version: '{{ appserver.openedx_release }}'
notifier_version: '{{ appserver.openedx_release }}'
xqueue_version: '{{ appserver.openedx_release }}'
certs_version: '{{ appserver.openedx_release }}'

# Features
EDXAPP_FEATURES:
  USE_MICROSITES: false
  AUTH_USE_OPENID: false
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_INSTRUCTOR_ANALYTICS: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: false
  ENABLE_PEARSON_HACK_TEST: false
  SUBDOMAIN_BRANDING: false
  SUBDOMAIN_COURSE_LISTINGS: false
  PREVIEW_LMS_BASE: '{{ instance.lms_preview_domain }}'
  ENABLE_DJANGO_ADMIN_SITE: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true

{% if github_admin_username_list %}# Users
COMMON_USER_INFO:{% for github_username in github_admin_username_list %}
  - name: {{ github_username }}
    github: true
    type: admin{% endfor %}{% endif %}

# Workers
EDXAPP_WORKER_DEFAULT_STOPWAITSECS: 1200
