# edxapp
EDXAPP_PLATFORM_NAME: '{{ instance.name }}'
EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_NGINX_SSL_PORT: 443
EDXAPP_SITE_NAME: '{{ instance.domain }}'
EDXAPP_LMS_SITE_NAME: $EDXAPP_SITE_NAME
EDXAPP_LMS_BASE: $EDXAPP_SITE_NAME
EDXAPP_PREVIEW_LMS_BASE: $EDXAPP_SITE_NAME

EDXAPP_CMS_SITE_NAME: '{{ instance.domain }}:18010'
EDXAPP_CMS_BASE: $EDXAPP_SITE_NAME

# Forum environment settings
FORUM_RACK_ENV: 'production'
FORUM_SINATRA_ENV: 'production'

# Emails
EDXAPP_CONTACT_EMAIL: '{{ instance.email }}'
EDXAPP_TECH_SUPPORT_EMAIL: $EDXAPP_CONTACT_EMAIL
EDXAPP_BUGS_EMAIL: $EDXAPP_CONTACT_EMAIL
EDXAPP_FEEDBACK_SUBMISSION_EMAIL: $EDXAPP_CONTACT_EMAIL
EDXAPP_DEFAULT_FROM_EMAIL: $EDXAPP_CONTACT_EMAIL
EDXAPP_DEFAULT_FEEDBACK_EMAIL: $EDXAPP_CONTACT_EMAIL
EDXAPP_SERVER_EMAIL: $EDXAPP_CONTACT_EMAIL
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: $EDXAPP_CONTACT_EMAIL

# Misc
EDXAPP_TIME_ZONE: 'UTC'

# Pin down dependencies to specific (known to be compatible) commits.
edx_platform_repo: '{{ instance.repository_url }}'
edx_platform_version: '{{ instance.commit_id }}'
edx_ansible_source_repo: 'https://github.com/edx/configuration.git'
configuration_version: 'master'

# Features
EDXAPP_FEATURES:
  USE_MICROSITES: false
  AUTH_USE_OPENID: false
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_INSTRUCTOR_ANALYTICS: true
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: false
  ENABLE_PEARSON_HACK_TEST: false
  SUBDOMAIN_BRANDING: false
  SUBDOMAIN_COURSE_LISTINGS: false
  PREVIEW_LMS_BASE: $EDXAPP_PREVIEW_LMS_BASE
  ENABLE_DJANGO_ADMIN_SITE: true
  ALLOW_ALL_ADVANCED_COMPONENTS: true
